export const STOCK_OBJECT = 'STOCK_OBJECT';
export const ENTRY_OBJECT_PUSH = 'ENTRY_OBJECT_PUSH';
export const ENTRY_OBJECT_UPDATE = 'ENTRY_OBJECT_UPDATE';
export const STOCK_OBJECT_PUSH = 'STOCK_OBJECT_PUSH';
export const STOCK_COLLECTION = 'STOCK_COLLECTION';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const TOKEN = 'TOKEN';
